-- ModulNest compatibility schema generated by export-modulnest.sh
-- Clean installs use app/Database/schema/* and selected module Database files.

-- Source: app/Database/schema/core.sql
-- Modulon Basis-Schema für Benutzer, Rollen und Berechtigungen
-- Zielsystem: MySQL 8+

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    username VARCHAR(40) NULL UNIQUE,
    email VARCHAR(190) NOT NULL UNIQUE,
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    dashboard_auto_refresh_enabled TINYINT(1) NOT NULL DEFAULT 1,
    dashboard_auto_refresh_interval_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    password_hash VARCHAR(255) NOT NULL,
    is_blocked TINYINT(1) NOT NULL DEFAULT 0,
    totp_secret VARCHAR(255) NULL,
    totp_enabled TINYINT(1) NOT NULL DEFAULT 0,
    webauthn_enabled TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS username VARCHAR(40) NULL,
    ADD COLUMN IF NOT EXISTS timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    ADD COLUMN IF NOT EXISTS dashboard_auto_refresh_enabled TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS dashboard_auto_refresh_interval_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    ADD COLUMN IF NOT EXISTS is_blocked TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS totp_enabled TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS webauthn_enabled TINYINT(1) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_permission (
    role_id BIGINT UNSIGNED NOT NULL,
    permission_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id) REFERENCES permissions(id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_role (
    user_id BIGINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS remember_tokens (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_remember_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_remember_tokens_user_id (user_id),
    INDEX idx_remember_tokens_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS modules (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(255) NULL,
    route_prefix VARCHAR(120) NOT NULL UNIQUE,
    access_level ENUM('public', 'user', 'admin') NOT NULL DEFAULT 'public',
    handler ENUM('native', 'placeholder', 'legacy') NOT NULL DEFAULT 'native',
    legacy_entry VARCHAR(255) NULL,
    admin_entry VARCHAR(255) NULL,
    enable_overlay TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    show_in_header TINYINT(1) NOT NULL DEFAULT 1,
    show_on_home TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE modules
    ADD COLUMN IF NOT EXISTS description VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS handler ENUM('native', 'placeholder', 'legacy') NOT NULL DEFAULT 'native',
    ADD COLUMN IF NOT EXISTS legacy_entry VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS admin_entry VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS enable_overlay TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS show_in_header TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS show_on_home TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE modules
    MODIFY COLUMN handler ENUM('native', 'placeholder', 'legacy') NOT NULL DEFAULT 'native';

CREATE TABLE IF NOT EXISTS app_settings (
    `key` VARCHAR(120) PRIMARY KEY,
    `value` TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schema_migrations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    migration_key VARCHAR(190) NOT NULL,
    scope VARCHAR(40) NOT NULL,
    module_key VARCHAR(120) NULL,
    description VARCHAR(255) NULL,
    checksum CHAR(64) NULL,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_schema_migrations_key (migration_key),
    INDEX idx_schema_migrations_scope_module (scope, module_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS webauthn_credentials (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    label VARCHAR(120) NOT NULL,
    credential_id VARCHAR(255) NOT NULL UNIQUE,
    public_key TEXT NOT NULL,
    sign_count BIGINT UNSIGNED NULL,
    transports VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_webauthn_credentials_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_webauthn_credentials_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recovery_codes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    code_hash CHAR(64) NOT NULL,
    used_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recovery_codes_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_recovery_codes_user_id (user_id),
    INDEX idx_recovery_codes_code_hash (code_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Source: app/Modules/Banking/Database/schema.sql
-- Banking-Modul Zielstruktur (native, usergebundene Migration aus Legacy-Banking)
CREATE TABLE IF NOT EXISTS banking_migration_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    target_user_id BIGINT UNSIGNED NOT NULL,
    source_database VARCHAR(120) NOT NULL DEFAULT 'banking',
    source_snapshot_label VARCHAR(190) NULL,
    source_transactions_count INT UNSIGNED NOT NULL DEFAULT 0,
    source_rules_count INT UNSIGNED NOT NULL DEFAULT 0,
    source_conditions_count INT UNSIGNED NOT NULL DEFAULT 0,
    imported_transactions_count INT UNSIGNED NOT NULL DEFAULT 0,
    imported_rules_count INT UNSIGNED NOT NULL DEFAULT 0,
    imported_conditions_count INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('planned', 'dry_run', 'running', 'completed', 'failed', 'rolled_back') NOT NULL DEFAULT 'planned',
    notes TEXT NULL,
    started_at TIMESTAMP NULL DEFAULT NULL,
    finished_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_migration_runs_user
        FOREIGN KEY (target_user_id) REFERENCES users(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX idx_banking_migration_runs_user (target_user_id),
    INDEX idx_banking_migration_runs_status (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_accounts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    migration_run_id BIGINT UNSIGNED NULL,
    legacy_account_key VARCHAR(190) NULL,
    account_identifier VARCHAR(190) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    iban VARCHAR(34) NULL,
    bic VARCHAR(11) NULL,
    currency CHAR(3) NOT NULL DEFAULT 'EUR',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_accounts_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_accounts_migration_run
        FOREIGN KEY (migration_run_id) REFERENCES banking_migration_runs(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uq_banking_accounts_user_identifier (user_id, account_identifier),
    INDEX idx_banking_accounts_user_active (user_id, is_active),
    INDEX idx_banking_accounts_user_iban (user_id, iban),
    INDEX idx_banking_accounts_migration_run (migration_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_categories (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    migration_run_id BIGINT UNSIGNED NULL,
    name VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120) NOT NULL,
    color VARCHAR(20) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_categories_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_categories_migration_run
        FOREIGN KEY (migration_run_id) REFERENCES banking_migration_runs(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uq_banking_categories_user_normalized (user_id, normalized_name),
    INDEX idx_banking_categories_user_sort (user_id, sort_order),
    INDEX idx_banking_categories_migration_run (migration_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_import_batches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NULL,
    migration_run_id BIGINT UNSIGNED NULL,
    source_type ENUM('legacy_migration', 'csv', 'manual', 'other') NOT NULL DEFAULT 'legacy_migration',
    original_filename VARCHAR(255) NULL,
    file_sha256 CHAR(64) NULL,
    status ENUM('pending', 'running', 'completed', 'failed', 'rolled_back') NOT NULL DEFAULT 'pending',
    imported_count INT UNSIGNED NOT NULL DEFAULT 0,
    updated_count INT UNSIGNED NOT NULL DEFAULT 0,
    skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_summary TEXT NULL,
    started_at TIMESTAMP NULL DEFAULT NULL,
    finished_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_import_batches_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_import_batches_account
        FOREIGN KEY (account_id) REFERENCES banking_accounts(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_banking_import_batches_migration_run
        FOREIGN KEY (migration_run_id) REFERENCES banking_migration_runs(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX idx_banking_import_batches_user_status (user_id, status),
    INDEX idx_banking_import_batches_account (account_id),
    INDEX idx_banking_import_batches_file_hash (user_id, file_sha256),
    INDEX idx_banking_import_batches_migration_run (migration_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_transactions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NULL,
    category_id BIGINT UNSIGNED NULL,
    import_batch_id BIGINT UNSIGNED NULL,
    migration_run_id BIGINT UNSIGNED NULL,
    legacy_id INT UNSIGNED NULL,
    booking_date DATE NOT NULL,
    value_date DATE NULL,
    booking_text VARCHAR(255) NULL,
    purpose TEXT NULL,
    counterparty_name VARCHAR(255) NULL,
    counterparty_iban VARCHAR(64) NULL,
    counterparty_bic VARCHAR(20) NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'EUR',
    raw_info TEXT NULL,
    legacy_category_name VARCHAR(120) NULL,
    transaction_hash CHAR(64) NULL,
    booking_status ENUM('gebucht', 'vorgemerkt') NOT NULL DEFAULT 'gebucht',
    legacy_created_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_transactions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_transactions_account
        FOREIGN KEY (account_id) REFERENCES banking_accounts(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_banking_transactions_category
        FOREIGN KEY (category_id) REFERENCES banking_categories(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_banking_transactions_import_batch
        FOREIGN KEY (import_batch_id) REFERENCES banking_import_batches(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_banking_transactions_migration_run
        FOREIGN KEY (migration_run_id) REFERENCES banking_migration_runs(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uq_banking_transactions_user_legacy (user_id, legacy_id),
    UNIQUE KEY uq_banking_transactions_user_hash (user_id, transaction_hash),
    INDEX idx_banking_transactions_user_account_date (user_id, account_id, booking_date),
    INDEX idx_banking_transactions_user_value_date (user_id, value_date),
    INDEX idx_banking_transactions_user_status (user_id, booking_status),
    INDEX idx_banking_transactions_user_category (user_id, category_id),
    INDEX idx_banking_transactions_user_amount (user_id, amount),
    INDEX idx_banking_transactions_migration_run (migration_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_recurring_rules (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NULL,
    category_id BIGINT UNSIGNED NULL,
    migration_run_id BIGINT UNSIGNED NULL,
    legacy_id INT UNSIGNED NULL,
    name VARCHAR(190) NOT NULL,
    interval_type VARCHAR(40) NOT NULL,
    notes TEXT NULL,
    rule_type VARCHAR(40) NULL,
    group_label VARCHAR(120) NULL,
    active_from DATE NULL,
    active_to DATE NULL,
    period_mode VARCHAR(40) NULL,
    due_day TINYINT UNSIGNED NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    legacy_created_at TIMESTAMP NULL DEFAULT NULL,
    legacy_updated_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_recurring_rules_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_recurring_rules_account
        FOREIGN KEY (account_id) REFERENCES banking_accounts(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_banking_recurring_rules_category
        FOREIGN KEY (category_id) REFERENCES banking_categories(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_banking_recurring_rules_migration_run
        FOREIGN KEY (migration_run_id) REFERENCES banking_migration_runs(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uq_banking_recurring_rules_user_legacy (user_id, legacy_id),
    INDEX idx_banking_recurring_rules_user_active (user_id, is_active),
    INDEX idx_banking_recurring_rules_user_type (user_id, rule_type),
    INDEX idx_banking_recurring_rules_user_interval (user_id, interval_type),
    INDEX idx_banking_recurring_rules_user_group (user_id, group_label),
    INDEX idx_banking_recurring_rules_migration_run (migration_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_recurring_rule_conditions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    recurring_rule_id BIGINT UNSIGNED NOT NULL,
    migration_run_id BIGINT UNSIGNED NULL,
    legacy_id INT UNSIGNED NULL,
    field VARCHAR(80) NOT NULL,
    operator VARCHAR(40) NOT NULL,
    value VARCHAR(255) NOT NULL,
    legacy_created_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_recurring_rule_conditions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_recurring_rule_conditions_rule
        FOREIGN KEY (recurring_rule_id) REFERENCES banking_recurring_rules(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_banking_recurring_rule_conditions_migration_run
        FOREIGN KEY (migration_run_id) REFERENCES banking_migration_runs(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uq_banking_recurring_rule_conditions_user_legacy (user_id, legacy_id),
    UNIQUE KEY uq_banking_recurring_rule_conditions_rule_legacy (recurring_rule_id, legacy_id),
    INDEX idx_banking_recurring_rule_conditions_user (user_id),
    INDEX idx_banking_recurring_rule_conditions_rule (recurring_rule_id),
    INDEX idx_banking_recurring_rule_conditions_field_operator (field, operator),
    INDEX idx_banking_recurring_rule_conditions_migration_run (migration_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banking_dashboard_cache (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    cache_scope VARCHAR(60) NOT NULL,
    period_key VARCHAR(20) NOT NULL,
    data_hash CHAR(64) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_banking_dashboard_cache_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY uq_banking_dashboard_cache_scope (user_id, cache_scope, period_key),
    INDEX idx_banking_dashboard_cache_user_updated (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Source: app/Modules/Dashboard/Database/schema.sql
-- Dashboard-Grundlage (usergebundene, mehrfach einbindbare Widgets)
CREATE TABLE IF NOT EXISTS dashboard_widgets (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    widget_type ENUM('links', 'tasks', 'notes') NOT NULL,
    title VARCHAR(120) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    layout_width TINYINT UNSIGNED NOT NULL DEFAULT 6,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_dashboard_widgets_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_dashboard_widgets_user (user_id),
    INDEX idx_dashboard_widgets_user_sort (user_id, sort_order),
    INDEX idx_dashboard_widgets_user_type (user_id, widget_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dashboard_link_folders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    widget_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(120) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_dashboard_link_folders_widget
        FOREIGN KEY (widget_id) REFERENCES dashboard_widgets(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_dashboard_link_folders_widget (widget_id),
    INDEX idx_dashboard_link_folders_widget_sort (widget_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dashboard_links (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    widget_id BIGINT UNSIGNED NOT NULL,
    folder_id BIGINT UNSIGNED NULL,
    title VARCHAR(180) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    favicon_url VARCHAR(2048) NULL,
    favicon_host VARCHAR(190) NULL,
    favicon_last_checked_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_dashboard_links_widget
        FOREIGN KEY (widget_id) REFERENCES dashboard_widgets(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_dashboard_links_folder
        FOREIGN KEY (folder_id) REFERENCES dashboard_link_folders(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX idx_dashboard_links_widget (widget_id),
    INDEX idx_dashboard_links_widget_sort (widget_id, sort_order),
    INDEX idx_dashboard_links_folder (folder_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dashboard_tasks (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    widget_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    details TEXT NULL,
    link_url VARCHAR(2048) NULL,
    priority TINYINT UNSIGNED NOT NULL DEFAULT 0,
    due_at TIMESTAMP NULL DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_done TINYINT(1) NOT NULL DEFAULT 0,
    done_at TIMESTAMP NULL DEFAULT NULL,
    repeat_type ENUM('none', 'daily', 'weekly', 'monthly') NOT NULL DEFAULT 'none',
    repeat_time TIME NULL DEFAULT NULL,
    repeat_weekday TINYINT UNSIGNED NULL,
    repeat_month_mode ENUM('first_day', 'middle_day', 'last_day', 'fixed_day', 'ordinal_weekday') NULL,
    repeat_month_day TINYINT UNSIGNED NULL,
    repeat_month_ordinal TINYINT UNSIGNED NULL,
    repeat_month_weekday TINYINT UNSIGNED NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_dashboard_tasks_widget
        FOREIGN KEY (widget_id) REFERENCES dashboard_widgets(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_dashboard_tasks_widget (widget_id),
    INDEX idx_dashboard_tasks_widget_done_sort (widget_id, is_done, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE dashboard_tasks
    ADD COLUMN IF NOT EXISTS link_url VARCHAR(2048) NULL AFTER details,
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER due_at,
    ADD COLUMN IF NOT EXISTS repeat_type ENUM('none', 'daily', 'weekly', 'monthly') NOT NULL DEFAULT 'none' AFTER done_at,
    ADD COLUMN IF NOT EXISTS repeat_time TIME NULL DEFAULT NULL AFTER repeat_type,
    ADD COLUMN IF NOT EXISTS repeat_weekday TINYINT UNSIGNED NULL AFTER repeat_time,
    ADD COLUMN IF NOT EXISTS repeat_month_mode ENUM('first_day', 'middle_day', 'last_day', 'fixed_day', 'ordinal_weekday') NULL AFTER repeat_weekday,
    ADD COLUMN IF NOT EXISTS repeat_month_day TINYINT UNSIGNED NULL AFTER repeat_month_mode,
    ADD COLUMN IF NOT EXISTS repeat_month_ordinal TINYINT UNSIGNED NULL AFTER repeat_month_day,
    ADD COLUMN IF NOT EXISTS repeat_month_weekday TINYINT UNSIGNED NULL AFTER repeat_month_ordinal;

ALTER TABLE dashboard_tasks
    MODIFY COLUMN repeat_month_mode ENUM('first_day', 'middle_day', 'last_day', 'fixed_day', 'ordinal_weekday') NULL;

CREATE TABLE IF NOT EXISTS dashboard_notes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    widget_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(180) NULL,
    content MEDIUMTEXT NOT NULL,
    textarea_height INT UNSIGNED NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_pinned TINYINT(1) NOT NULL DEFAULT 0,
    is_archived TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_dashboard_notes_widget
        FOREIGN KEY (widget_id) REFERENCES dashboard_widgets(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_dashboard_notes_widget (widget_id),
    INDEX idx_dashboard_notes_widget_sort (widget_id, is_pinned, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE dashboard_notes
    ADD COLUMN IF NOT EXISTS textarea_height INT UNSIGNED NULL AFTER content;


-- Source: app/Modules/News/Database/schema.sql
CREATE TABLE IF NOT EXISTS news_entries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    excerpt VARCHAR(400) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    type ENUM('news', 'update', 'release', 'note') NOT NULL DEFAULT 'news',
    version VARCHAR(30) NULL,
    status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
    published_at TIMESTAMP NULL DEFAULT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_news_entries_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_news_entries_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX idx_news_entries_status_published (status, published_at),
    INDEX idx_news_entries_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Source: app/Modules/SneakPreview/Database/schema.sql
CREATE TABLE IF NOT EXISTS sneak_preview_entries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    legacy_id INT NULL,
    sneak_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    release_date_de DATE NULL,
    poster_path VARCHAR(255) NULL,
    poster_tmdb_path VARCHAR(255) NULL,
    tmdb_id INT NULL,
    overview TEXT NULL,
    genres VARCHAR(255) NULL,
    runtime INT NULL,
    certification VARCHAR(20) NULL,
    original_language VARCHAR(20) NULL,
    production_countries VARCHAR(255) NULL,
    vote_average DECIMAL(3,1) NULL,
    trailer_key VARCHAR(32) NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_sneak_preview_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_sneak_preview_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY uniq_sneak_preview_legacy_id (legacy_id),
    INDEX idx_sneak_preview_sneak_date (sneak_date),
    INDEX idx_sneak_preview_title (title),
    INDEX idx_sneak_preview_location (location),
    INDEX idx_sneak_preview_release_date (release_date_de),
    INDEX idx_sneak_preview_tmdb_id (tmdb_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sneak_preview_settings (
    `key` VARCHAR(120) PRIMARY KEY,
    `value` TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Source: app/Database/seeds/core.sql
-- Optionaler Standard-Seed für die Registrierung (attachRoleByName('user')).
INSERT IGNORE INTO roles (name) VALUES ('user');
INSERT IGNORE INTO roles (name) VALUES ('admin');
INSERT IGNORE INTO app_settings (`key`, `value`) VALUES ('public_registration_enabled', '1');

-- Fachmodule werden nicht im Core-Schema hart verdrahtet.
-- Native Module werden bei Bedarf in der Modulverwaltung per Auto-Discovery aus app/Modules/* initial angelegt.
-- Legacy-Module können weiterhin manuell in der Modulverwaltung registriert werden.


-- Source: app/Modules/News/Database/seeds.sql
INSERT INTO news_entries
    (title, slug, excerpt, content, type, version, status, published_at, created_by, updated_by)
VALUES
    (
        'v0.1.0-alpha1 – Projektstart und Grundgerüst',
        'v0-1-0-alpha1-projektstart-und-grundgeruest',
        'Start des Projekts mit Front Controller, Router und Basis-Views.',
        'Erste Grundlage für Modulon als eigenständiges PHP-Projekt.\n\n- Front Controller in public/index.php\n- mod_rewrite über .htaccess\n- Core-Klassen für Request, Response, Router und Application',
        'release',
        '0.1.0-alpha1',
        'published',
        '2026-04-11 09:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-alpha2 – Datenbank, Benutzer und Rollen',
        'v0-1-0-alpha2-datenbank-benutzer-und-rollen',
        'Schema für Benutzer-, Rollen- und Berechtigungsdaten eingeführt.',
        'Der Datenbank-Unterbau wurde für Authentifizierung und Rechteverwaltung vorbereitet.\n\n- users, roles, permissions, user_role, role_permission\n- PDO-Anbindung und ENV-basierte DB-Konfiguration\n- Seed-Rollen user/admin',
        'update',
        '0.1.0-alpha2',
        'published',
        '2026-04-11 11:30:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-beta1 – Login, Session und Remember-Me',
        'v0-1-0-beta1-login-session-und-remember-me',
        'Auth-Flow mit Session-Lifecycle und persistentem Login umgesetzt.',
        'Das Auth-System wurde von Registrierung bis Logout durchgezogen.\n\n- password_hash/password_verify\n- Idle-Timeout und absolute Session-Laufzeit\n- Remember-Me mit gehashten, rotierenden Tokens',
        'release',
        '0.1.0-beta1',
        'published',
        '2026-04-11 14:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-beta2 – 2FA mit TOTP, WebAuthn und Recovery Codes',
        'v0-1-0-beta2-2fa-totp-webauthn-recovery-codes',
        'Mehrstufige 2FA-Optionen für produktionsnahe Sicherheit ergänzt.',
        'Die Sicherheitsfunktionen wurden deutlich erweitert.\n\n- TOTP inkl. Setup-Verifikation\n- WebAuthn/Passkeys mit mehreren Credentials\n- Recovery Codes, gehasht gespeichert und einmalig nutzbar',
        'release',
        '0.1.0-beta2',
        'published',
        '2026-04-11 17:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-rc1 – Adminbereich und Modulverwaltung',
        'v0-1-0-rc1-adminbereich-und-modulverwaltung',
        'Adminwerkzeuge und dynamische Modulrouten aus der Datenbank eingeführt.',
        'Aus dem Grundsystem wurde ein administrierbares Modulsystem.\n\n- /admin mit Modulverwaltung\n- Zugriffsstufen public/user/admin\n- Aktivierte Module werden zur Laufzeit als Routen geladen',
        'release',
        '0.1.0-rc1',
        'published',
        '2026-04-11 20:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-rc2 – Legacy-Integration und Overlay-Injection',
        'v0-1-0-rc2-legacy-integration-und-overlay-injection',
        'Legacy-Apps wurden als Module anbaubar und zentral steuerbar gemacht.',
        'Der Fokus lag auf Integration bestehender Anwendungen ohne Rewrite.\n\n- Legacy-Dispatcher mit Datei-/Asset-Auslieferung\n- Admin-Entry-Unterstützung pro Modul\n- Serverseitige Overlay-Injection für angemeldete Modulon-User',
        'update',
        '0.1.0-rc2',
        'published',
        '2026-04-12 12:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-rc3 – UI-System, Dark Mode und Branding',
        'v0-1-0-rc3-ui-system-dark-mode-und-branding',
        'Gemeinsames Layout, konsistente Komponenten und Branding-Assets eingebaut.',
        'Die Oberfläche wurde über alle Kernbereiche vereinheitlicht.\n\n- Zentrales Layout mit Navbar/Footer\n- Light/Dark Theme über CSS-Variablen\n- Modulon-Branding (Icon/Logo) und Overlay-Feinschliff',
        'update',
        '0.1.0-rc3',
        'published',
        '2026-04-14 10:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0 – Native News-/Changelog-Modul live',
        'v0-1-0-native-news-changelog-modul-live',
        'Das erste native Nicht-Legacy-Modul ersetzt den News-Platzhalter.',
        'Das News-Modul dient als zentrale Entwicklungsübersicht für Modulon.\n\n- Öffentliche Übersicht und Detailseiten unter /news\n- Admin-CRUD unter /admin/news\n- Struktur für Releases, Updates, Notes und Versionierung',
        'release',
        '0.1.0',
        'published',
        '2026-04-15 09:00:00',
        NULL,
        NULL
    ),
    (
        'v0.3.0 – Dashboard, Mail-Hub und System-Hardening',
        'v0-3-0-dashboard-mail-hub-system-hardening',
        'Großes Funktionsupdate mit Dashboard-Widgets, modernisiertem Mail-Modul, Systemcheck und konsolidierter Benutzer-/Admin-UX.',
        'Seit dem letzten GitHub-Upload wurde Modulon in mehreren Bereichen substanziell erweitert.\n\n- Dashboard als natives Modul mit usergebundenen Widgets (Links, Aufgaben, Notizen), AJAX-Interaktionen, wiederkehrenden Aufgaben inkl. Reaktivierung und konsistentem Formular-UX-Flow.\n- Links-Widget robust gemacht: URL-Analyse, sichere Favicon-Erkennung, lokales Favicon-Handling, Bearbeiten/Löschen und verbesserte Fehlerbehandlung.\n- Profilbereich ausgebaut (Profil/Sicherheit/Einstellungen), inklusive benutzerbezogener Zeitzone als Grundlage für zeitbasierte Features.\n- Admin- und Modularchitektur weiter vereinheitlicht: native Modultypen, transparente Modul-Einstiege, Sortierung/Sichtbarkeit und konsistentere Navigation.\n- Neues natives Modul Systeminfo mit strukturierten Karten, Header-Feinschliff, Serverzeit/Zeitzone und erweitertem Systemcheck.\n- Mail-Modul als Multi-Account-Hub ausgebaut: Kontoverwaltung, Ordner/Favoriten, Nachrichtenliste mit getrennter Sortierung/Gruppierung, sichere Nachrichtendarstellung, Compose/Reply und SMTP-Versand.\n- Mail-Transport modernisiert: `webklex/php-imap` + `symfony/mailer`, ohne ext-imap, mit klaren Voraussetzungen und degradiertem Verhalten bei fehlenden Runtime-Requirements.\n- Zentrales Error-/Debug-Handling auf Basis von APP_ENV/APP_DEBUG ergänzt, inklusive Logging und sauberer Development-/Production-Trennung.\n- README, Architekturdoku und Projekt-Memory entlang der neuen Architekturstände aktualisiert.',
        'release',
        '0.3.0',
        'published',
        '2026-04-20 18:00:00',
        NULL,
        NULL
    ),
    (
        'v0.3.1 – Mail-Viewer stabilisiert, Auth-Debugging und lokales E2E-Setup',
        'v0-3-1-mail-viewer-stabilisiert-auth-debugging-e2e-setup',
        'Fokus-Update auf Mail-UX, robustes HTML-Rendering, Login-Diagnostik und reproduzierbare Browser-E2E-Tests.',
        'Dieses Update schließt die letzten großen Mail-UX-/Rendering-Lücken und stärkt die Entwicklungsqualität.\n\n- Mail-Arbeitsbereich stabilisiert: konsistente Split-View mit Vorschau-Toggle, persistenter Pane-Größe und robustem Verhalten beim Nachrichtenwechsel.\n- HTML-Mail-Rendering gehärtet: iframe-basierte, isolierte Darstellung mit deutlich originalgetreuerem Layout bei weiterhin strikter Sanitization und kontrollierter Bildfreigabe.\n- Bilderfreigabe im Vorschau-Kontext korrigiert: kein Navigieren auf nackte `partial=1`-Ansichten mehr, sondern Reload im bestehenden Preview-Flow.\n- Mail-Listenperformance und Bedienfluss weiter verbessert (Header-/Index-Cache, Nachladen, Absenderansicht-Flow, konsistente Navigation Arbeitsbereich/Verfassen/Konten & Ordner).\n- Login-Debugging ausgebaut: fehlgeschlagene Logins werden intern strukturiert protokolliert (ohne Passwort-Leak), inklusive klarer Fehlklassifikation zur schnelleren Ursachenanalyse.\n- Lokales Browser-E2E-Testsetup ergänzt: Python + pytest + Playwright (Chromium), inklusive Smoke-Tests für Startseite, Login und Mail-Grundfluss.\n- System-/Runtime-Verhalten präzisiert: HEAD-Requests sauber auf GET-Routen aufgelöst, ohne Response-Body.\n- Dokumentation und Projekt-Memory entlang des neuen Stands aktualisiert.',
        'release',
        '0.3.1',
        'published',
        '2026-04-22 11:30:00',
        NULL,
        NULL
    ),
    (
        'v0.4.0 – Native Banking-App und modulare Laufzeit',
        'v0-4-0-native-banking-app-und-modulare-laufzeit',
        'Großes Architektur- und Funktionsupdate mit nativem Banking-Modul, Modul-Auto-Discovery, modularer Admin-/User-Navigation und weiteren Dashboard-Verbesserungen.',
        'Dieses Release bringt Modulon deutlich näher an das Ziel einer wirklich modularen Plattform.\n\n- Native Modul-Laufzeit eingeführt: Fachmodule können Routen, Untermenüs, Adminbereiche, User-Navigation und Binding-Metadaten selbst registrieren.\n- Modul-Auto-Discovery ergänzt: neue Modulordner werden in der Modulverwaltung erkannt und deaktiviert angelegt, während die manuelle Registrierung als Fallback erhalten bleibt.\n- News, Dashboard, Mail, Profil, Systeminfo und Banking laufen über eigene Modulklassen statt über zentrale Core-Sonderverdrahtung.\n- Native Banking-App stark ausgebaut: Dashboard, Umsatzliste, Monatsübersicht, wiederkehrende Regeln, Fälligkeitsstatus, Sparkassen-CSV-Import, Duplikaterkennung und kontrolliertes Löschen eigener Duplikate.\n- Banking-Legacy-Fallback bleibt parallel unter `/banking-old` erreichbar, während die native UI ausschließlich user_id-gescoped auf Modulon-Tabellen arbeitet.\n- Banking-Import robuster gemacht: optionale Kategorie-Spalte, bessere Erkennung vorhandener/vorgemerkter Buchungen und Batch-/Rollback-Grundlage.\n- Dashboard verfeinert: Profilabhängige Settings-Links, User-Dropdown aus Modul-Navigation, Auto-Refresh-Pause bei Dialogen und abgesicherte lange Linktitel.\n- Adminbereich modularisiert: Admin-Dropdown, modulbasierte Admin-Navigation und bereinigte Modulverwaltung.\n- Viele UI-Details in Banking, Dashboard und Profil korrigiert, inklusive Zahlenformatierung, Tooltips, Sticky-Tabellenkopf, Statusfarben und klarerer Hilfetexte.\n- README, technische Architektur und Projekt-Memory wurden an den neuen Modulstand angepasst.',
        'release',
        '0.4.0',
        'published',
        '2026-04-27 18:00:00',
        NULL,
        NULL
    ),
    (
        'v0.5.0 alpha – Erster öffentlicher ModulNest-Release',
        'v0-5-0-alpha-erster-oeffentlicher-modulnest-release',
        'ModulNest wurde erstmals als öffentliches GitHub-Projekt mit Bootstrap-Installer, Source-/Bundled-Paketen und MIT-Lizenz veröffentlicht.',
        'Mit v0.5.0 wurde aus dem privaten Arbeitsprojekt Modulon der erste öffentliche ModulNest-Alpha-Stand.\n\n- Öffentlicher Produktname auf ModulNest festgelegt; Modulon bleibt der interne Core-/Arbeitsname.\n- Bereinigter Public-Export nach `/srv/http/modulnest` und Veröffentlichung im GitHub-Repo `ChobitsChii/ModulNest`.\n- Source- und Bundled-ZIP-Pakete als Release-Assets eingeführt: Source ohne `vendor/` für Composer-Installationen, Bundled mit `vendor/` für normale Webspaces ohne Composer.\n- `build/update/stable.json` als maschinenlesbare Release-Metadaten mit Paket-URLs und SHA256-Prüfsummen ergänzt.\n- Bootstrap-Installer `install.php` aufgebaut: Systemcheck, Paketwahl, Datenbanktest, erstes Admin-Konto, Modul-Auswahl und Installationslog.\n- Download und Installation werden per SHA256 geprüft und ZIP-Slip-sicher entpackt.\n- Installer erzeugt lokale Konfiguration, führt das Schema aus, legt den ersten Admin an und versucht sich nach erfolgreicher Installation selbst zu löschen.\n- README und öffentliche Dokumentation wurden auf ModulNest ausgerichtet und stark aufgeräumt.\n- MIT-Lizenz ergänzt.',
        'release',
        '0.5.0',
        'published',
        '2026-05-08 14:16:40',
        NULL,
        NULL
    ),
    (
        'v0.5.1 alpha – PHP-FPM-/FastCGI-Hotfix',
        'v0-5-1-alpha-php-fpm-fastcgi-hotfix',
        'Hotfix für Apache/PHP-FPM-Setups: mod_php-spezifische .htaccess-Direktiven wurden entfernt.',
        'Dieses Patch-Release behebt einen HTTP-500-Fehler auf modernen PHP-FPM-/FastCGI-/CGI-Setups.\n\n- `php_value`- und `php_flag`-Direktiven aus `public/.htaccess` entfernt.\n- `.htaccess` enthält damit nur noch Rewrite-/Routing-Regeln, die auch ohne mod_php funktionieren.\n- `public/.user.ini.example` als Vorlage für optionale PHP-Limits ergänzt.\n- Dokumentation zu PHP-FPM/FastCGI, Hosting-Panels, `php.ini`, PHP-FPM-Pool-Konfiguration und `.user.ini` aktualisiert.\n- Bestehende Installationen müssen für diesen Fehler nicht neu installiert werden; das Ersetzen von `public/.htaccess` reicht.',
        'release',
        '0.5.1',
        'published',
        '2026-05-08 17:11:06',
        NULL,
        NULL
    ),
    (
        'v0.6.0 alpha – Admin-Updates-Modul',
        'v0-6-0-alpha-admin-updates-modul',
        'ModulNest erhält erstmals ein Admin-Modul, um offizielle Release-ZIPs aus stable.json zu prüfen, vorzubereiten und zu installieren.',
        'v0.6.0 bringt die erste robuste Update-Funktion für bestehende ModulNest-Installationen.\n\n- Neues Admin-Updates-Modul unter `/admin/updates`.\n- Updateprüfung über die offizielle `stable.json`.\n- Für normale Webinstallationen wird das Bundled-ZIP bevorzugt, damit kein Composer auf dem Zielsystem nötig ist.\n- Release-ZIP wird heruntergeladen, per SHA256 geprüft und ZIP-Slip-sicher entpackt.\n- Update-Vorbereitung nutzt ein Staging-Verzeichnis unter `storage/updates`.\n- Vor dem Überschreiben wird ein Datei-Backup unter `storage/backups/updates` erstellt.\n- Einfacher Wartungsmodus über `storage/maintenance.flag` vorbereitet.\n- Schutzliste verhindert das Überschreiben oder Kopieren sensibler Bereiche wie `.env`, `storage`, `.git`, `.local`, `install.php` und lokaler Runtime-Daten.\n- `public/.htaccess`, App-Dateien, Assets, Dokumentation, Composer-Dateien, Paketmetadaten und `vendor/` aus Bundled-Paketen können aktualisiert werden.\n- v1 führt keine automatische riskante Datenbankmigration aus; mögliche DB-Änderungen werden als Hinweis behandelt.\n- Für bestehende 0.5.x-Installationen muss das Updates-Modul einmalig manuell eingespielt und aktiviert werden.',
        'release',
        '0.6.0',
        'published',
        '2026-05-08 19:05:48',
        NULL,
        NULL
    ),
    (
        'v0.6.1 alpha – Versionsanzeige und Update-UX korrigiert',
        'v0-6-1-alpha-versionsanzeige-und-update-ux-korrigiert',
        'Patch-Release für die Versionslogik nach Updates und mehrere UI-Korrekturen im Admin-Updates-Modul.',
        'v0.6.1 korrigiert die wichtigste Nacharbeit am neuen Updates-Modul.\n\n- Die angezeigte App-Version kommt jetzt zuverlässig aus `app/Config/version.php`.\n- Alte `.env`-Einträge wie `APP_VERSION` oder `APP_CHANNEL` überschreiben die Code-/Release-Version nicht mehr.\n- Neue Installationen schreiben `APP_VERSION` und `APP_CHANNEL` nicht mehr in `.env`, damit Datei-Updates die sichtbare Version nicht blockieren.\n- Update-State wird nach erfolgreichem Update normalisiert, sodass ein bereits installiertes Update nicht weiter als verfügbar angezeigt wird.\n- Updates-Seite zeigt Datums- und Zeitangaben deutsch formatiert und mit der Zeitzone des aktuellen Users.\n- Externe Links im Updates-Modul öffnen in einem neuen Tab und sind mit Icon markiert.\n- Versions-/Channel-Anzeige ist im Dark Theme besser lesbar.\n- Live-Update von 0.6.0 auf 0.6.1 funktioniert über das Updates-Modul ohne manuellen Dateiersatz, sofern das 0.6.0-Updates-Modul bereits installiert und aktiv ist.',
        'release',
        '0.6.1',
        'published',
        '2026-05-08 23:11:45',
        NULL,
        NULL
    )
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    excerpt = VALUES(excerpt),
    content = VALUES(content),
    type = VALUES(type),
    version = VALUES(version),
    status = VALUES(status),
    published_at = VALUES(published_at),
    updated_by = VALUES(updated_by),
    updated_at = CURRENT_TIMESTAMP;

