<?php
declare(strict_types=1);
namespace Modulon\Core\Modules;
use PDO;use RuntimeException;use Throwable;
final class ModuleLifecycleService
{
    public function __construct(private readonly PDO $pdo,private readonly string $basePath,private readonly string $coreVersion,private readonly DatabaseBackupProviderInterface $backups,private readonly ModuleOperationLock $lock,private readonly ModulePackageInspector $inspector=new ModulePackageInspector(),private readonly DependencyResolver $dependencies=new DependencyResolver()){}
    /** @return array<string,mixed> */ public function install(string $package,?string $sha256=null,bool $activate=true,string $origin='local',?string $catalogSourceId=null,?int $catalogSequence=null): array {
        if(!in_array($origin,['local','manual-v2','catalog-managed'],true))throw new RuntimeException('Ungültige Modulherkunft.');
        $inspection=$this->inspector->inspect($package,$sha256);$m=$inspection['manifest'];$m->requireEnvironment($this->coreVersion);$this->dependencies->assertSatisfied($m,$this->installedVersions());$previous=$this->row($m->id);$currentSchema=(int)($previous['data_schema_version']??0);$compatible=$m->raw['data']['compatible_schema']??null;if($previous!==null&&$currentSchema>0&&($compatible===null||!DataSchemaConstraint::parse((string)$compatible)->matches($currentSchema)))throw new RuntimeException('Vorhandenes retained Datenschema ist mit diesem Release nicht kompatibel.');$effectiveSchema=max($currentSchema,$m->schemaVersion);$this->lock->acquire($m->id);$operation=$this->beginOperation($m->id,$previous===null?'install':'update',$previous['active_release_id']??null,null);$locator=new ModuleReleaseLocator($this->basePath);$releaseId=$m->version->value.'-'.substr($inspection['sha256'],0,12);$staging=$this->basePath.'/modules/'.$m->id.'/.staging-'.$operation;$root=$locator->releaseRoot($m->id,$releaseId);
        try{$this->phase($operation,'extracting');(new SafeArchiveExtractor())->extract($package,$staging);(new ModuleManifestReader())->read($staging.'/module.json');$this->phase($operation,'health_pre_switch');(new IsolatedHealthChecker($this->basePath))->check($staging);$this->phase($operation,'registering');if(is_dir($root))ModulePackageInspector::removeTree($root);if(!is_dir(dirname($root))&&!mkdir(dirname($root),0775,true)&&!is_dir(dirname($root)))throw new RuntimeException('Releaseordner kann nicht erstellt werden.');if(!rename($staging,$root))throw new RuntimeException('Atomare Release-Installation fehlgeschlagen.');$this->registerRelease($m,$releaseId,$root,$inspection['sha256']);(new ManagedModuleMigrationRunner($this->pdo))->run($m,$root);$this->copyAssets($m,$root,$locator->publicAssetRoot($m->id,$releaseId));$this->switchRelease($m,$releaseId,$activate,$effectiveSchema,$origin,$catalogSourceId,$catalogSequence);(new RuntimeCacheManager())->publishFreshRelease($root);$this->phase($operation,'health_post_switch');(new IsolatedHealthChecker($this->basePath))->check($root);$this->finish($operation);return $this->inspect($m->id);}catch(Throwable $e){if(is_dir($staging))ModulePackageInspector::removeTree($staging);$this->rollbackRegistry($m->id,$previous);$this->fail($operation,$e);throw $e;}finally{$this->lock->release();}}
    /** @return array<string,mixed> */ public function prepareAdoptionRelease(string $package,?string $sha256=null): array {
        $inspection=$this->inspector->inspect($package,$sha256);$m=$inspection['manifest'];$m->requireEnvironment($this->coreVersion);$this->dependencies->assertSatisfied($m,$this->installedVersions());if($this->row($m->id)!==null)throw new RuntimeException('Modul ist bereits installiert.');if($m->migrationsPath!==null)throw new RuntimeException('Vorbereitete Adoption unterstützt keine neuen Paketmigrationen.');$this->lock->acquire($m->id);$operation=$this->beginOperation($m->id,'install',null,null);$locator=new ModuleReleaseLocator($this->basePath);$releaseId=$m->version->value.'-'.substr($inspection['sha256'],0,12);$staging=$this->basePath.'/modules/'.$m->id.'/.staging-'.$operation;$root=$locator->releaseRoot($m->id,$releaseId);$assetRoot=$locator->publicAssetRoot($m->id,$releaseId);
        try{$this->phase($operation,'extracting');(new SafeArchiveExtractor())->extract($package,$staging);(new ModuleManifestReader())->read($staging.'/module.json');$this->phase($operation,'health_pre_switch');(new IsolatedHealthChecker($this->basePath))->check($staging);$this->phase($operation,'registering');if(is_dir($root))ModulePackageInspector::removeTree($root);if(!is_dir(dirname($root))&&!mkdir(dirname($root),0775,true)&&!is_dir(dirname($root)))throw new RuntimeException('Releaseordner kann nicht erstellt werden.');if(!rename($staging,$root))throw new RuntimeException('Atomare Release-Installation fehlgeschlagen.');$this->registerRelease($m,$releaseId,$root,$inspection['sha256']);$this->copyAssets($m,$root,$assetRoot);(new RuntimeCacheManager())->publishFreshRelease($root);$this->phase($operation,'health_post_switch');(new IsolatedHealthChecker($this->basePath))->check($root);$this->finish($operation);return ['module_id'=>$m->id,'module_name'=>$m->name,'description'=>$m->description,'route_prefix'=>$m->routePrefix,'access_level'=>$m->accessLevel,'version'=>$m->version->value,'release_id'=>$releaseId,'sha256'=>$inspection['sha256']];}catch(Throwable $e){if(is_dir($staging))ModulePackageInspector::removeTree($staging);if(is_dir($root))ModulePackageInspector::removeTree($root);if(is_dir($assetRoot))ModulePackageInspector::removeTree($assetRoot);$this->pdo->prepare('DELETE FROM module_data_resources WHERE module_id=?')->execute([$m->id]);$this->pdo->prepare('DELETE FROM module_releases WHERE module_id=? AND release_id=?')->execute([$m->id,$releaseId]);$this->fail($operation,$e);throw $e;}finally{$this->lock->release();}}
    /** @param list<string> $packages @return list<array<string,mixed>> */ public function installSelected(array $packages): array {$byId=[];$manifests=[];foreach($packages as $package){$manifest=$this->inspector->inspect($package)['manifest'];if(isset($byId[$manifest->id]))throw new RuntimeException('Modul wurde doppelt ausgewählt.');$byId[$manifest->id]=$package;$manifests[$manifest->id]=$manifest;}$graph=[];foreach($manifests as $id=>$manifest)$graph[$id]=array_values(array_filter(array_keys($manifest->dependencies),static fn($dep)=>isset($byId[$dep])));$result=[];foreach($this->dependencies->order($graph) as $id)$result[]=$this->install($byId[$id]);return $result;}
    public function update(string $package,?string $sha256=null,?int $catalogSequence=null): array {$preview=$this->inspector->inspect($package,$sha256);$current=$this->row($preview['manifest']->id);if($current===null)throw new RuntimeException('Modul ist nicht installiert.');if($preview['manifest']->version->compare(SemVer::parse((string)$current['installed_version']))<=0)throw new RuntimeException('Updateversion muss höher sein.');$tables=$this->resources($preview['manifest']->id,'tables');$backup=$this->backups->backup($preview['manifest']->id,$tables);$this->backups->verify($backup);try{return $this->install($package,$sha256,(bool)$current['is_active'],(string)$current['origin'],$current['catalog_source_id']!==null?(string)$current['catalog_source_id']:null,$catalogSequence??($current['catalog_sequence']!==null?(int)$current['catalog_sequence']:null));}catch(Throwable $e){$this->backups->restore($backup);throw $e;}}
    public function activate(string $id): void {$row=$this->row($id);if($row===null)throw new RuntimeException('Modul ist nicht installiert.');$release=$this->releaseManifest($id,(string)$row['active_release_id']);$this->dependencies->assertSatisfied($release,$this->activeVersions());$this->setActive($id,true);}
    public function deactivate(string $id): void {$this->assertNoActiveDependents($id);$this->setActive($id,false);}
    public function uninstall(string $id,bool $purge=false): void {ModuleId::assert($id);$this->assertNoActiveDependents($id);$this->lock->acquire($id);$op=$this->beginOperation($id,$purge?'purge':'uninstall',null,null);try{$row=$this->row($id);if($row===null)throw new RuntimeException('Modul ist nicht registriert.');if($purge){$backup=$this->backups->backup($id,$this->resources($id,'tables'));$this->backups->verify($backup);$this->pdo->prepare('UPDATE module_operations SET backup_reference=?,phase=? WHERE operation_id=?')->execute([$backup,'backup_verified',$op]);}$this->pdo->prepare('UPDATE modules SET is_active=0 WHERE id=?')->execute([$row['module_row_id']]);if($purge){$this->purgeData($id);$this->pdo->prepare('DELETE FROM module_installations WHERE module_id=?')->execute([$id]);$this->pdo->prepare('DELETE FROM modules WHERE module_key=?')->execute([$id]);}else{$this->pdo->prepare('UPDATE module_installations SET installed_version=NULL,active_release_id=NULL,retained_data=1 WHERE module_id=?')->execute([$id]);}$code=$this->basePath.'/modules/'.$id;if(is_dir($code))ModulePackageInspector::removeTree($code);$assets=$this->basePath.'/public/assets/modules/'.$id;if(is_dir($assets))ModulePackageInspector::removeTree($assets);if($purge){foreach(['storage/modules/'.$id,'storage/cache/modules/'.$id] as $relative)if(is_dir($this->basePath.'/'.$relative))ModulePackageInspector::removeTree($this->basePath.'/'.$relative);}$this->finish($op);}catch(Throwable $e){$this->fail($op,$e);throw $e;}finally{$this->lock->release();}}
    /** @return array<string,mixed> */ public function inspect(string $id): array {$row=$this->row($id);if($row===null)throw new RuntimeException('Modul nicht gefunden.');return $row+['resources'=>$this->allResources($id),'operations'=>$this->operations($id)];}
    /** @return list<array<string,mixed>> */ public function list(): array {return $this->pdo->query('SELECT i.*,m.name,m.route_prefix,m.access_level,m.is_active FROM module_installations i JOIN modules m ON m.id=i.module_row_id ORDER BY i.module_id')->fetchAll(PDO::FETCH_ASSOC);}
    private function registerRelease(ModuleManifest $m,string $releaseId,string $root,string $hash): void {$json=json_encode($m->raw,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);$s=$this->pdo->prepare("INSERT INTO module_releases(module_id,version,release_id,release_path,manifest_json,sha256,status) VALUES(?,?,?,?,?,?,'ready') ON DUPLICATE KEY UPDATE release_path=VALUES(release_path),manifest_json=VALUES(manifest_json),sha256=VALUES(sha256),status='ready'");$s->execute([$m->id,$m->version->value,$releaseId,$root,$json,$hash]);$pk=(int)$this->pdo->query('SELECT id FROM module_releases WHERE module_id='.$this->pdo->quote($m->id).' AND release_id='.$this->pdo->quote($releaseId))->fetchColumn();$this->pdo->prepare('DELETE FROM module_dependencies WHERE release_pk=?')->execute([$pk]);foreach(['required'=>$m->dependencies,'optional'=>$m->optionalDependencies,'conflict'=>$m->conflicts] as $kind=>$deps)foreach($deps as $id=>$range)$this->pdo->prepare('INSERT INTO module_dependencies VALUES(?,?,?,?)')->execute([$pk,$id,$range,$kind]);$this->pdo->prepare('DELETE FROM module_data_resources WHERE module_id=?')->execute([$m->id]);foreach($m->ownership as $type=>$items)foreach($items as $item)$this->pdo->prepare('INSERT INTO module_data_resources(module_id,resource_type,resource_key) VALUES(?,?,?)')->execute([$m->id,$type,$item]);}
    private function switchRelease(ModuleManifest $m,string $releaseId,bool $active,int $effectiveSchema,string $origin,?string $catalogSourceId,?int $catalogSequence): void {$this->pdo->beginTransaction();try{$find=$this->pdo->prepare('SELECT id FROM modules WHERE module_key=?');$find->execute([$m->id]);$rowId=$find->fetchColumn();if($rowId===false){$s=$this->pdo->prepare("INSERT INTO modules(module_key,name,description,route_prefix,access_level,handler,is_active,show_in_header,show_on_home) VALUES(?,?,?,?,?,'native',?,1,1)");$s->execute([$m->id,$m->name,$m->description,$m->routePrefix,$m->accessLevel,$active?1:0]);$rowId=$this->pdo->lastInsertId();}else{$this->pdo->prepare('UPDATE modules SET name=?,description=?,route_prefix=?,access_level=?,is_active=? WHERE id=?')->execute([$m->name,$m->description,$m->routePrefix,$m->accessLevel,$active?1:0,$rowId]);}$s=$this->pdo->prepare("INSERT INTO module_installations(module_id,module_row_id,origin,catalog_source_id,catalog_sequence,installed_version,active_release_id,data_schema_version,retained_data,health_status,package_sha256) VALUES(?,?,?,?,?,?,?,?,0,'healthy',(SELECT sha256 FROM module_releases WHERE module_id=? AND release_id=?)) ON DUPLICATE KEY UPDATE origin=VALUES(origin),catalog_source_id=VALUES(catalog_source_id),catalog_sequence=VALUES(catalog_sequence),installed_version=VALUES(installed_version),active_release_id=VALUES(active_release_id),data_schema_version=VALUES(data_schema_version),retained_data=0,health_status='healthy',package_sha256=VALUES(package_sha256)");$s->execute([$m->id,$rowId,$origin,$catalogSourceId,$catalogSequence,$m->version->value,$releaseId,$effectiveSchema,$m->id,$releaseId]);$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    private function setActive(string $id,bool $active): void {ModuleId::assert($id);$s=$this->pdo->prepare('UPDATE modules m JOIN module_installations i ON i.module_row_id=m.id SET m.is_active=? WHERE i.module_id=? AND i.installed_version IS NOT NULL');$s->execute([$active?1:0,$id]);if($s->rowCount()!==1)throw new RuntimeException('Aktivierungszustand konnte nicht geändert werden.');}
    private function purgeData(string $id): void {$this->pdo->exec('SET FOREIGN_KEY_CHECKS=0');try{foreach($this->resources($id,'tables') as $table){if(!preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/D',$table))throw new RuntimeException('Unsichere registrierte Tabelle.');$this->pdo->exec('DROP TABLE IF EXISTS `'.$table.'`');}}finally{$this->pdo->exec('SET FOREIGN_KEY_CHECKS=1');}foreach($this->resources($id,'settings') as $key)$this->pdo->prepare('DELETE FROM app_settings WHERE `key`=?')->execute([$key]);$this->pdo->prepare("DELETE FROM schema_migrations WHERE scope='module' AND module_key=?")->execute([$id]);$this->pdo->prepare('DELETE FROM module_data_resources WHERE module_id=?')->execute([$id]);$this->pdo->prepare('DELETE FROM module_releases WHERE module_id=?')->execute([$id]);}
    private function copyAssets(ModuleManifest $m,string $root,string $target): void {if($m->assetsPath===null)return;$source=$root.'/'.$m->assetsPath;if(!is_dir($source))throw new RuntimeException('Assetpfad fehlt.');if(is_dir($target))ModulePackageInspector::removeTree($target);foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($source,\FilesystemIterator::SKIP_DOTS),\RecursiveIteratorIterator::SELF_FIRST) as $item){$dest=$target.'/'.substr($item->getPathname(),strlen($source)+1);if($item->isLink())throw new RuntimeException('Asset-Link ist verboten.');if($item->isDir()){@mkdir($dest,0775,true);}else{@mkdir(dirname($dest),0775,true);if(!copy($item->getPathname(),$dest))throw new RuntimeException('Assetkopie fehlgeschlagen.');}}}
    private function installedVersions(): array {$rows=$this->pdo->query('SELECT module_id,installed_version FROM module_installations WHERE installed_version IS NOT NULL')->fetchAll(PDO::FETCH_KEY_PAIR);return array_map('strval',$rows);}
    private function activeVersions(): array {$rows=$this->pdo->query('SELECT i.module_id,i.installed_version FROM module_installations i JOIN modules m ON m.id=i.module_row_id WHERE i.installed_version IS NOT NULL AND m.is_active=1')->fetchAll(PDO::FETCH_KEY_PAIR);return array_map('strval',$rows);}
    private function row(string $id): ?array {$s=$this->pdo->prepare('SELECT i.*,m.name,m.route_prefix,m.access_level,m.is_active FROM module_installations i JOIN modules m ON m.id=i.module_row_id WHERE i.module_id=?');$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    private function resources(string $id,string $type): array {$s=$this->pdo->prepare('SELECT resource_key FROM module_data_resources WHERE module_id=? AND resource_type=? ORDER BY resource_key');$s->execute([$id,$type]);return array_map('strval',$s->fetchAll(PDO::FETCH_COLUMN));}
    private function allResources(string $id): array {$s=$this->pdo->prepare('SELECT resource_type,resource_key FROM module_data_resources WHERE module_id=? ORDER BY resource_type,resource_key');$s->execute([$id]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    private function operations(string $id): array {$s=$this->pdo->prepare('SELECT * FROM module_operations WHERE module_id=? ORDER BY created_at DESC');$s->execute([$id]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    private function beginOperation(string $id,string $type,?string $old,?string $new): string {$uuid=sprintf('%s-%s-4%s-%s%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),substr(bin2hex(random_bytes(2)),1),dechex(random_int(8,11)),substr(bin2hex(random_bytes(2)),1),bin2hex(random_bytes(6)));$this->pdo->prepare("INSERT INTO module_operations(operation_id,module_id,operation_type,old_release_id,new_release_id,phase,status) VALUES(?,?,?,?,?,'starting','running')")->execute([$uuid,$id,$type,$old,$new]);return $uuid;}
    private function phase(string $op,string $phase): void {$this->pdo->prepare('UPDATE module_operations SET phase=? WHERE operation_id=?')->execute([$phase,$op]);}
    private function finish(string $op): void {$this->pdo->prepare("UPDATE module_operations SET phase='complete',status='succeeded' WHERE operation_id=?")->execute([$op]);}
    private function fail(string $op,Throwable $e): void {$this->pdo->prepare("UPDATE module_operations SET status='failed',error_message=? WHERE operation_id=?")->execute([$e->getMessage(),$op]);}
    private function assertNoActiveDependents(string $id): void {$s=$this->pdo->prepare("SELECT DISTINCT r.module_id FROM module_dependencies d JOIN module_releases r ON r.id=d.release_pk JOIN module_installations i ON i.module_id=r.module_id AND i.active_release_id=r.release_id JOIN modules m ON m.id=i.module_row_id WHERE d.target_module_id=? AND d.dependency_kind='required' AND m.is_active=1");$s->execute([$id]);$dependent=$s->fetchColumn();if($dependent!==false)throw new RuntimeException("Aktives Modul hängt davon ab: {$dependent}");}
    private function releaseManifest(string $id,string $releaseId): ModuleManifest {$s=$this->pdo->prepare('SELECT manifest_json FROM module_releases WHERE module_id=? AND release_id=?');$s->execute([$id,$releaseId]);$json=$s->fetchColumn();if(!is_string($json))throw new RuntimeException('Aktives Release fehlt.');$raw=json_decode($json,true,64,JSON_THROW_ON_ERROR);return ModuleManifest::fromArray($raw);}
    private function rollbackRegistry(string $id,?array $previous): void {try{if($previous===null){$row=$this->row($id);if($row!==null){$this->pdo->prepare('UPDATE modules SET is_active=0 WHERE id=?')->execute([$row['module_row_id']]);$this->pdo->prepare("UPDATE module_installations SET installed_version=NULL,active_release_id=NULL,health_status='failed' WHERE module_id=?")->execute([$id]);}return;}$this->pdo->prepare('UPDATE modules SET is_active=? WHERE id=?')->execute([(int)$previous['is_active'],$previous['module_row_id']]);$this->pdo->prepare('UPDATE module_installations SET installed_version=?,active_release_id=?,data_schema_version=?,retained_data=?,health_status=? WHERE module_id=?')->execute([$previous['installed_version'],$previous['active_release_id'],$previous['data_schema_version'],$previous['retained_data'],$previous['health_status'],$id]);}catch(Throwable){/* Das ursprüngliche Fehlerbild bleibt im Journal; Recovery kann den Pointer prüfen. */}}
}
