<?php
declare(strict_types=1);
namespace Modulon\Core\Modules\Catalog;
use DateTimeImmutable;use InvalidArgumentException;use Modulon\Core\Modules\{ModuleId,SemVer,VersionConstraint};
final class CatalogSchemaValidator
{
    public function root(string $json):array{$d=$this->decode($json);$this->keys($d,['schema_version','catalog_id','sequence','generated_at','expires_at','signing_keys','modules']);if(($d['schema_version']??null)!==1||!is_string($d['catalog_id'])||!preg_match('/^[a-z][a-z0-9.-]+$/D',$d['catalog_id'])||!is_int($d['sequence'])||$d['sequence']<1)throw new InvalidArgumentException('Ungültiger Katalogkopf.');$this->dateTime($d['generated_at']);$this->dateTime($d['expires_at']);$this->list($d['signing_keys'],'signing_keys');foreach($d['signing_keys'] as $key){$this->keys($key,['key_id','algorithm','fingerprint']);if(!is_string($key['key_id'])||$key['algorithm']!=='Ed25519'||!preg_match('/^[a-f0-9]{64}$/D',(string)$key['fingerprint']))throw new InvalidArgumentException('Ungültige Signing-Key-Metadaten.');}$this->list($d['modules'],'modules');$ids=[];foreach($d['modules'] as $module){$this->keys($module,['id','path','sha256']);$id=ModuleId::assert((string)$module['id']);if(isset($ids[$id]))throw new InvalidArgumentException('Doppelte Modul-ID im Katalog.');$ids[$id]=true;$this->relative((string)$module['path']);$this->sha((string)$module['sha256']);}return $d;}
    public function signature(string $json):array{$d=$this->decode($json);$this->keys($d,['key_id','signature']);if(!is_string($d['key_id'])||!is_string($d['signature']))throw new InvalidArgumentException('Ungültige Signaturdatei.');return $d;}
    public function module(string $json):array{$d=$this->decode($json);$schema=$d['schema_version']??null;if($schema===1){$required=['schema_version','id','name','description','homepage','repository','license','authors','releases'];}elseif($schema===2){$required=['schema_version','id','name','description','homepage','repository','license','authors','history','releases'];}else throw new InvalidArgumentException('Ungültiges Modulindexschema.');$this->keysWithOptional($d,$required,['adoption','deprecated','deprecation_reason']);if($schema===2)$this->history($d['history']);ModuleId::assert((string)$d['id']);foreach(['name','description','homepage','repository','license'] as $f)if(!is_string($d[$f]))throw new InvalidArgumentException("Ungültiges Feld: {$f}");foreach(['homepage','repository'] as $f)if($d[$f]!==''&&filter_var($d[$f],FILTER_VALIDATE_URL)===false)throw new InvalidArgumentException("Ungültige URL: {$f}");$this->strings($d['authors'],'authors');$this->list($d['releases'],'releases');if($d['releases']===[])throw new InvalidArgumentException('Modulindex ohne Releases.');if(isset($d['deprecated'])&&!is_bool($d['deprecated']))throw new InvalidArgumentException('deprecated muss ein Boolean sein.');if(isset($d['deprecation_reason'])&&(!is_string($d['deprecation_reason'])||trim($d['deprecation_reason'])===''))throw new InvalidArgumentException('deprecation_reason muss ein nicht-leerer String sein.');$versions=[];$historyByVersion=$schema===2?array_column($d['history'],null,'version'):[];foreach($d['releases'] as $release){$this->release($release,$schema);if(isset($versions[$release['version']]))throw new InvalidArgumentException('Doppelte Release-Version.');$versions[$release['version']]=true;if($schema===2){$history=$historyByVersion[$release['version']]??null;if(!is_array($history)||$history['changes']!==$release['release_notes']['changes'])throw new InvalidArgumentException('Release Notes stimmen nicht mit der Modulhistorie überein.');}}return $d;}
    private function release(mixed $r,int $schema):void{$this->keys($r,['version','channel','release_notes','core','php','dependencies','migration_count','package','signing_key_id','signing_fingerprint','signature','published_at']);SemVer::parse((string)$r['version']);if(!in_array($r['channel'],['stable','beta','nightly'],true))throw new InvalidArgumentException('Ungültiger Release-Channel.');if($schema===1){if(!is_string($r['release_notes']))throw new InvalidArgumentException('Ungültige Release Notes.');}else{$this->keys($r['release_notes'],['summary','changes']);if(!is_string($r['release_notes']['summary'])||trim($r['release_notes']['summary'])==='')throw new InvalidArgumentException('Release-Notes-Zusammenfassung fehlt.');$this->strings($r['release_notes']['changes'],'release_notes.changes');}foreach(['signing_key_id','signing_fingerprint','signature'] as $f)if(!is_string($r[$f]))throw new InvalidArgumentException("Ungültiges Releasefeld: {$f}");if(!is_int($r['migration_count'])||$r['migration_count']<0)throw new InvalidArgumentException('Ungültige Migrationsanzahl.');VersionConstraint::parse((string)$r['core']);VersionConstraint::parse((string)$r['php']);$this->dateTime($r['published_at']);if(!is_array($r['dependencies'])||($r['dependencies']!==[]&&array_is_list($r['dependencies'])))throw new InvalidArgumentException('dependencies muss ein Objekt sein.');foreach($r['dependencies'] as $id=>$range){ModuleId::assert((string)$id);VersionConstraint::parse((string)$range);}$p=$r['package'];$this->keys($p,['location','size','sha256']);$this->relative((string)$p['location']);if(!is_int($p['size'])||$p['size']<1)throw new InvalidArgumentException('Ungültige Paketgröße.');$this->sha((string)$p['sha256']);if(!preg_match('/^[a-f0-9]{64}$/D',$r['signing_fingerprint']))throw new InvalidArgumentException('Ungültiger Fingerprint.');}
    private function history(mixed $history):void{$this->list($history,'history');if($history===[])throw new InvalidArgumentException('Modulhistorie fehlt.');$versions=[];$previous=null;foreach($history as $entry){$this->keys($entry,['version','date','changes']);$version=SemVer::parse((string)$entry['version']);if(isset($versions[$version->value]))throw new InvalidArgumentException('Doppelte Version in der Modulhistorie.');if($previous instanceof SemVer&&$previous->compare($version)<=0)throw new InvalidArgumentException('Modulhistorie muss absteigend sortiert sein.');$versions[$version->value]=true;$previous=$version;if(!is_string($entry['date'])||!preg_match('/^\d{4}-\d{2}-\d{2}$/D',$entry['date']))throw new InvalidArgumentException('Ungültiges Datum in der Modulhistorie.');$this->strings($entry['changes'],'history.changes');}}
    private function decode(string $json):array{if(strlen($json)>1048576||!mb_check_encoding($json,'UTF-8'))throw new InvalidArgumentException('Katalog-JSON ist zu groß oder nicht UTF-8.');$d=json_decode($json,true,64,JSON_THROW_ON_ERROR);if(!is_array($d)||array_is_list($d))throw new InvalidArgumentException('Katalogdatei muss ein Objekt sein.');return $d;}
    private function keys(mixed $d,array $keys):void{if(!is_array($d)||array_is_list($d))throw new InvalidArgumentException('Objekt erwartet.');$actual=array_keys($d);sort($actual);sort($keys);if($actual!==$keys)throw new InvalidArgumentException('Katalogschema enthält fehlende oder unbekannte Felder.');}
    private function keysWithOptional(mixed $d,array $required,array $optional):void{if(!is_array($d)||array_is_list($d))throw new InvalidArgumentException('Objekt erwartet.');$actual=array_keys($d);foreach($required as $key)if(!in_array($key,$actual,true))throw new InvalidArgumentException('Katalogschema enthält fehlende Felder.');foreach($actual as $key)if(!in_array($key,$required,true)&&!in_array($key,$optional,true))throw new InvalidArgumentException('Katalogschema enthält unbekannte Felder.');}
    private function list(mixed $v,string $field):void{if(!is_array($v)||!array_is_list($v))throw new InvalidArgumentException("{$field} muss eine Liste sein.");}
    private function strings(mixed $v,string $field):void{$this->list($v,$field);if($v===[])throw new InvalidArgumentException("{$field} darf nicht leer sein.");foreach($v as $item)if(!is_string($item)||trim($item)==='')throw new InvalidArgumentException("Ungültiger Eintrag in {$field}.");}
    private function dateTime(mixed $v):void{if(!is_string($v))throw new InvalidArgumentException('Zeitstempel muss Text sein.');$d=DateTimeImmutable::createFromFormat(DATE_ATOM,$v);if(!$d||$d->format(DATE_ATOM)!==$v)throw new InvalidArgumentException('Zeitstempel muss RFC3339 sein.');}
    private function relative(string $v):void{if($v===''||str_starts_with($v,'/')||str_contains(str_replace('\\','/',$v),'../')||preg_match('#^[a-z]+:#i',$v))throw new InvalidArgumentException('Unsicherer relativer Katalogpfad.');}
    private function sha(string $v):void{if(!preg_match('/^[a-f0-9]{64}$/D',$v))throw new InvalidArgumentException('Ungültiger SHA-256.');}
}
