<?php
declare(strict_types=1);
use Modulon\Core\{CsrfGuard,CsrfTokenManager,Request,Response,Router,Session};
require dirname(__DIR__, 2).'/vendor/autoload.php';
function homepage_csrf_assert(bool $ok,string $msg):void{if(!$ok){fwrite(STDERR,"FAIL: $msg\n");exit(1);}}
if(session_status()===PHP_SESSION_ACTIVE){session_destroy();}session_id('homepage-csrf-'.bin2hex(random_bytes(4)));
$session=new Session();$tokens=new CsrfTokenManager($session);$token=$tokens->token();$router=new Router();$router->setAccessGuard(static fn(Request $r,string $a):?Response=>null);$router->setCsrfGuard((new CsrfGuard($tokens))->handle(...));$handler=static fn(Request $r):Response=>new Response('ok');
$routes=['/admin/homepage/publish','/admin/homepage/blocks/create','/admin/homepage/blocks/update','/admin/homepage/blocks/toggle','/admin/homepage/blocks/visibility','/admin/homepage/blocks/delete','/admin/homepage/blocks/move'];foreach($routes as $route){$router->post($route,$handler,'admin');}
$call=static function(string $route,array $input=[],array $headers=[])use($router):array{$response=$router->dispatch(new Request('POST',$route,$input,[],[],$headers));ob_start();$response->send();return [http_response_code(),(string)ob_get_clean()];};
foreach($routes as $route){[$status,$body]=$call($route,['_csrf'=>$token]);homepage_csrf_assert($status===200&&$body==='ok',$route.' accepts valid token');[$status]=$call($route);homepage_csrf_assert($status===419,$route.' blocks missing token');[$status]=$call($route,['_csrf'=>str_repeat('f',64)]);homepage_csrf_assert($status===419,$route.' blocks bad token');}
[$status,$body]=$call('/admin/homepage/blocks/toggle',[],['X-CSRF-Token'=>$token,'Accept'=>'application/json']);homepage_csrf_assert($status===200&&$body==='ok','header token accepted');[$status,$body]=$call('/admin/homepage/blocks/move',[],['Accept'=>'application/json']);$json=json_decode($body,true);homepage_csrf_assert($status===419&&is_array($json)&&($json['error']??null)==='csrf_token_invalid','json 419');$session->remove(CsrfTokenManager::SESSION_KEY);$other=$tokens->token();[$status]=$call('/admin/homepage/publish',['_csrf'=>$token]);homepage_csrf_assert($status===419,'other session blocked');$moduleSource=(string)file_get_contents(dirname(__DIR__,2).'/app/Modules/Homepage/HomepageModule.php');foreach($routes as $route){homepage_csrf_assert(str_contains($moduleSource,"'$route'"),'route exists: '.$route);$routeSuffix=substr($route,strlen('/admin/homepage'));homepage_csrf_assert(preg_match("~router->post\\('".preg_quote($route,'~')."'.*?'admin'\\);~",$moduleSource)===1,'route uses secure default: '.$routeSuffix);}fwrite(STDOUT,"Homepage CSRF smoke test passed.\n");
