<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/vendor/autoload.php';
use Modulon\Core\Database\MigrationRunner;use Modulon\Core\Modules\{ModuleLifecycleService,ModuleOperationLock,ModulePackageBuilder,ModulePackageInspector,ModuleReleaseLocator,ModuleRuntimeSnapshot,PdoLogicalBackupProvider};
function lifecycle_assert(bool $condition,string $message):void{if(!$condition){fwrite(STDERR,"FAIL: {$message}\n");exit(1);}}
function lifecycle_env(string $path):array{$r=[];foreach(file($path,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$line=trim($line);if($line===''||$line[0]==='#'||!str_contains($line,'='))continue;[$k,$v]=explode('=',$line,2);$r[trim($k)]=trim($v," \t\"'");}return $r;}
$root=dirname(__DIR__,2);$env=lifecycle_env($root.'/.env');$server=new PDO('mysql:host='.($env['DB_HOST']??'127.0.0.1').';port='.($env['DB_PORT']??'3306').';charset='.($env['DB_CHARSET']??'utf8mb4'),$env['DB_USER']??'',$env['DB_PASS']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$database='modulnest_module_v2_'.bin2hex(random_bytes(4));$tmp=sys_get_temp_dir().'/modulnest-module-v2-'.bin2hex(random_bytes(5));$server->exec('CREATE DATABASE `'.$database.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
try{mkdir($tmp.'/bin',0775,true);copy($root.'/bin/module-health.php',$tmp.'/bin/module-health.php');symlink($root.'/vendor',$tmp.'/vendor');
 $server->exec('USE `'.$database.'`');(new MigrationRunner($server,$root))->run([]);$builder=new ModulePackageBuilder();$zip01=$tmp.'/0.1.zip';$zip02=$tmp.'/0.2.zip';$hash01=$builder->build($root.'/tests/Fixtures/module-packages-v2/example-notes-0.1.0',$zip01);$hash02=$builder->build($root.'/tests/Fixtures/module-packages-v2/example-notes-0.2.0',$zip02);$service=new ModuleLifecycleService($server,$tmp,'1.2.0',new PdoLogicalBackupProvider($server,$tmp.'/storage/backups/modules'),new ModuleOperationLock($tmp.'/storage/locks/modules'));
 $installed=$service->install($zip01,$hash01);lifecycle_assert($installed['installed_version']==='0.1.0'&&(int)$installed['is_active']===1,'Install/Aktivierung fehlgeschlagen.');$server->exec("INSERT INTO example_notes_v2(title,body) VALUES('bleibt','erhalten')");$snapshot=ModuleRuntimeSnapshot::capture($server,new ModuleReleaseLocator($tmp));lifecycle_assert($snapshot->get('example.example-notes')?->version==='0.1.0','Runtime-Snapshot fehlt.');$service->deactivate('example.example-notes');lifecycle_assert((int)$service->inspect('example.example-notes')['is_active']===0,'Deaktivierung fehlgeschlagen.');$service->activate('example.example-notes');
 $updated=$service->update($zip02,$hash02);lifecycle_assert($updated['installed_version']==='0.2.0'&&(int)$updated['data_schema_version']===2,'Update fehlgeschlagen.');lifecycle_assert((int)$server->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='example_notes_v2' AND COLUMN_NAME='is_pinned'")->fetchColumn()===1,'additive 0.2-Migration fehlt.');lifecycle_assert((int)$server->query('SELECT COUNT(*) FROM example_notes_v2')->fetchColumn()===1,'Update verlor Moduldaten.');
 $service->uninstall('example.example-notes');$retained=$service->inspect('example.example-notes');lifecycle_assert($retained['installed_version']===null&&(int)$retained['retained_data']===1,'Retain-Uninstall falsch.');lifecycle_assert((int)$server->query("SELECT COUNT(*) FROM schema_migrations WHERE module_key='example.example-notes'")->fetchColumn()===2,'Retain löschte Migrationshistorie.');$service->install($zip02,$hash02);lifecycle_assert((int)$server->query('SELECT COUNT(*) FROM example_notes_v2')->fetchColumn()===1,'Reinstall übernahm retained data nicht.');
 $service->uninstall('example.example-notes',true);lifecycle_assert((int)$server->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='example_notes_v2'")->fetchColumn()===0,'Purge ließ Tabelle stehen.');lifecycle_assert((int)$server->query("SELECT COUNT(*) FROM schema_migrations WHERE module_key='example.example-notes'")->fetchColumn()===0,'Purge ließ exakte Migrationshistorie stehen.');lifecycle_assert((int)$server->query("SELECT COUNT(*) FROM module_operations WHERE module_id='example.example-notes'")->fetchColumn()>=4,'Purge löschte Audit-Historie.');
 $service->install($zip01,$hash01);lifecycle_assert((int)$server->query("SELECT COUNT(*) FROM schema_migrations WHERE module_key='example.example-notes'")->fetchColumn()===1,'Clean reinstall führte Migration nicht neu aus.');
}finally{$server->exec('DROP DATABASE IF EXISTS `'.$database.'`');if(is_link($tmp.'/vendor'))unlink($tmp.'/vendor');if(is_dir($tmp))ModulePackageInspector::removeTree($tmp);}fwrite(STDOUT,"Module lifecycle v2 smoke passed.\n");
