<?php

declare(strict_types=1);

use Modulon\Core\Database\MigrationRunner;
use Modulon\Modules\Wiki\{GitHubWikiClient, WikiRepository, WikiSearchHighlighter, WikiSearchIndexer, WikiSearchService, WikiService};

require dirname(__DIR__, 2) . '/vendor/autoload.php';

function wiki_search_assert(bool $condition,string $message):void{if(!$condition){fwrite(STDERR,"FAIL: {$message}\n");exit(1);}}
function wiki_search_env(string $path):array{$result=[];foreach(file($path,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$line=trim($line);if($line===''||$line[0]==='#'||!str_contains($line,'='))continue;[$key,$value]=explode('=',$line,2);$result[trim($key)]=trim($value," \t\"'");}return $result;}
function wiki_search_zip(array $files):string{$path=tempnam(sys_get_temp_dir(),'wiki-search-');$zip=new ZipArchive();$zip->open($path,ZipArchive::OVERWRITE);foreach($files as $name=>$content)$zip->addFromString('fixture/docs/'.$name,$content);$zip->close();$body=(string)file_get_contents($path);unlink($path);return $body;}
function wiki_search_remove(string $path):void{if(!is_dir($path))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $entry)$entry->isDir()&&!$entry->isLink()?rmdir($entry->getPathname()):unlink($entry->getPathname());rmdir($path);}

$root=dirname(__DIR__,2);$env=wiki_search_env($root.'/.env');$server=new PDO('mysql:host='.($env['DB_HOST']??'127.0.0.1').';port='.($env['DB_PORT']??'3306').';charset=utf8mb4',$env['DB_USER']??'',$env['DB_PASS']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$database='modulnest_wiki_search_'.bin2hex(random_bytes(4));$base=sys_get_temp_dir().'/modulnest-wiki-search-'.bin2hex(random_bytes(5));$server->exec('CREATE DATABASE `'.$database.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
try{
 $server->exec('USE `'.$database.'`');(new MigrationRunner($server,$root))->run(['Wiki']);$repo=new WikiRepository($server);$repo->saveSource(['owner'=>'ChobitsChii','repo'=>'ModulNest','ref'=>'main','root'=>'docs','enabled'=>1]);$indexer=new WikiSearchIndexer($server);$service=new WikiService($repo,$server,$base,new GitHubWikiClient(),$indexer);$search=new WikiSearchService($server,$indexer,$base.'/storage/wiki/content');
 $first=wiki_search_zip(['README.md'=>"# Dokumentation\n\nWillkommen bei ModulNest.",'configuration.md'=>"# ModulNest Konfiguration\n\n## WebAuthn und Sicherheit\n\nDie WEBAUTHN_RP_ID und CSRF-Konfiguration schützt Anmeldungen. stable.json enthält Update-Metadaten.\n\n```php\nView::csrfField(\$csrf_token);\n```",'development/security.md'=>"# Sicherheit entwickeln\n\nCSRF schützt schreibende Routen.",'hidden.md'=>"---\nhidden: true\n---\n# Geheime Suche"]);$service->syncArchive($repo->source(),$first,str_repeat('a',40));
 $status=$search->status();wiki_search_assert($status['status']==='current'&&$status['pages']===3&&$status['terms']>5,'A successful sync must build a current persistent index for visible pages.');
 foreach(['Konfiguration','konfig','Konfigration','WebAuthn','CSRF','stable.json','csrfField'] as $query){$result=$search->search($query);wiki_search_assert($result['available']&&$result['results']!==[],"Expected result for {$query}.");}
 wiki_search_assert($search->search('ModulNest Konfiguration')['results'][0]['title']==='ModulNest Konfiguration','Exact title matches must rank first.');
 wiki_search_assert($search->search('Konfigration')['results'][0]['title']==='ModulNest Konfiguration','A constrained typo must resolve through trigram candidates.');
 wiki_search_assert(in_array('konfiguration',$search->search('Konfigration')['results'][0]['matched_terms'],true),'Fuzzy results must expose the actual matched index term for truthful highlighting.');
 wiki_search_assert($search->search('ä')['too_short']===true&&$search->search('x')['results']===[],'Very short queries must not trigger fuzzy search.');
 wiki_search_assert(mb_strlen($search->search(str_repeat('a',500))['query'])===WikiSearchService::MAX_QUERY_LENGTH,'Excessive queries must be capped before candidate lookup.');
 wiki_search_assert($search->search('<img src=x onerror=alert(1)>')['results']===[],'HTML-like query input must not be reflected as executable output.');
 $highlighted=WikiSearchHighlighter::html('<script>Banking banking ÄNDERUNG</script>',['banking','änderung']);wiki_search_assert(substr_count($highlighted,'<mark>')===3&&!str_contains($highlighted,'<script>'),'Highlighting must be case-insensitive, Unicode-aware, repeat all matches and escape untrusted source text.');
 $beforeDocs=(int)$server->query('SELECT COUNT(*) FROM wiki_search_documents')->fetchColumn();$incremental=$indexer->synchronize((int)$repo->source()['id'],$base.'/storage/wiki/content');wiki_search_assert($incremental['indexed']===0&&$beforeDocs===(int)$server->query('SELECT COUNT(*) FROM wiki_search_documents')->fetchColumn(),'Unchanged pages must not be reindexed.');
 $second=wiki_search_zip(['README.md'=>"# Dokumentation\n\nWillkommen bei ModulNest.",'configuration.md'=>"# Geänderte Konfiguration\n\nPasskeys und Umlaute: Änderung für Österreich.",'new.md'=>"# Neue Seite\n\nRecovery und Migration"]);$sync=$service->syncArchive($repo->source(),$second,str_repeat('b',40));wiki_search_assert($sync['added']===1&&$sync['changed']===1&&$sync['deleted']===2,'Incremental sync must identify new, changed and deleted pages.');wiki_search_assert($search->search('schreibende')['results']===[]&&$search->search('Österreich')['results']!==[],'Deleted postings must vanish and changed Unicode content must replace its prior index.');
 $rebuild=$search->rebuild();wiki_search_assert($rebuild['pages']===3&&$rebuild['terms']>0,'A complete rebuild must reproduce the active index.');$oldTerms=(int)$server->query('SELECT COUNT(*) FROM wiki_search_terms')->fetchColumn();rename($base.'/storage/wiki/content/new.md',$base.'/storage/wiki/content/new.missing');$failed=false;try{$search->rebuild();}catch(Throwable){$failed=true;}rename($base.'/storage/wiki/content/new.missing',$base.'/storage/wiki/content/new.md');wiki_search_assert($failed&&$oldTerms===(int)$server->query('SELECT COUNT(*) FROM wiki_search_terms')->fetchColumn()&&$search->search('Recovery')['results']!==[],'A failed atomic rebuild must roll back and preserve the prior searchable index.');
 $migration=require $root.'/app/Modules/Wiki/Database/Migrations/20260904_010000_wiki_search.php';$migration->up($server,new Modulon\Core\Database\SchemaHelper($server));wiki_search_assert((int)$server->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name LIKE 'wiki_search_%'")->fetchColumn()===5,'The additive migration must be idempotent and create all search tables.');
}finally{$server->exec('DROP DATABASE IF EXISTS `'.$database.'`');wiki_search_remove($base);}
fwrite(STDOUT,"Wiki search smoke passed.\n");
