<?php
declare(strict_types=1);

use Modulon\Core\Database\{MigrationRunner, SchemaHelper};
use Modulon\Modules\Wiki\{GitHubWikiClient, WikiRepository, WikiService, WikiSyncException};

require dirname(__DIR__, 2) . '/vendor/autoload.php';

function wiki_local_integration_assert(bool $value, string $message): void { if (!$value) { fwrite(STDERR, "FAIL: {$message}\n"); exit(1); } }
/** @return array<string,string> */
function wiki_local_integration_env(string $path): array { $env=[];foreach(file($path,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$line=trim($line);if($line===''||$line[0]==='#'||!str_contains($line,'='))continue;[$key,$value]=explode('=',$line,2);$env[trim($key)]=trim($value," \t\"'");}return $env; }
function wiki_local_integration_zip(string $root): string { $file=tempnam(sys_get_temp_dir(),'wiki-local-fixture-');$zip=new ZipArchive();$zip->open($file,ZipArchive::OVERWRITE);$iterator=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root.'/docs',FilesystemIterator::SKIP_DOTS));foreach($iterator as $entry){if($entry->isFile())$zip->addFile($entry->getPathname(),'fixture/docs/'.substr($entry->getPathname(),strlen($root.'/docs/') ));}$zip->close();$archive=(string)file_get_contents($file);unlink($file);return $archive; }
/** @return array{pages:array<int,array<string,mixed>>,assets:array<int,array<string,mixed>>} */
function wiki_local_integration_index(PDO $pdo): array { return ['pages'=>$pdo->query('SELECT relative_path,route_path,title,sort_order,hidden FROM wiki_pages ORDER BY relative_path')->fetchAll(),'assets'=>$pdo->query('SELECT relative_path,mime_type FROM wiki_assets ORDER BY relative_path')->fetchAll()]; }
function wiki_local_integration_remove(string $directory): void { if(!is_dir($directory))return;$iterator=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($directory,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($iterator as $entry){$entry->isDir()&&!$entry->isLink()?rmdir($entry->getPathname()):unlink($entry->getPathname());}rmdir($directory); }

$root=dirname(__DIR__,2);$env=wiki_local_integration_env($root.'/.env');$server=new PDO('mysql:host='.($env['DB_HOST']??'127.0.0.1').';port='.($env['DB_PORT']??'3306').';charset='.($env['DB_CHARSET']??'utf8mb4'),$env['DB_USER']??'',$env['DB_PASS']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$database='modulnest_wiki_local_'.bin2hex(random_bytes(4));$base=sys_get_temp_dir().'/modulnest-wiki-local-'.bin2hex(random_bytes(5));$server->exec('CREATE DATABASE `'.$database.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
try {
    mkdir($base.'/docs/development',0775,true);mkdir($base.'/docs/images',0775,true);
    file_put_contents($base.'/docs/README.md',"---\ntitle: Local start\norder: 1\n---\n# Local start\n\n[Development](development/README.md)\n\n![Logo](images/logo.png)");
    file_put_contents($base.'/docs/development/README.md',"---\ntitle: Development\norder: 2\n---\n# Development\n\n[Guide](guide.md)");
    file_put_contents($base.'/docs/development/guide.md',"---\ntitle: Guide\norder: 3\n---\n# Guide");file_put_contents($base.'/docs/images/logo.png','PNG');
    $server->exec('USE `'.$database.'`');$legacyMigration=require $root.'/app/Modules/Wiki/Database/Migrations/20260902_164244_wiki.php';$legacyMigration->up($server,new SchemaHelper($server));$server->exec("INSERT INTO wiki_sources(repository_owner,repository_name,ref_name,docs_root,enabled) VALUES ('ChobitsChii','ModulNest','main','docs',1)");(new MigrationRunner($server,$root))->run(['Wiki']);
    $repo=new WikiRepository($server);$legacySource=$repo->source();wiki_local_integration_assert(($legacySource['source_type']??'')==='github'&&($legacySource['active_source_type']??'')==='github','A legacy GitHub source without source_type must migrate to GitHub for both configuration and active state.');
    $service=new WikiService($repo,$server,$base,new GitHubWikiClient());
    $service->saveLocalConfig('docs',false);wiki_local_integration_assert(($repo->source()['source_type']??'')==='local'&&(int)($repo->source()['enabled']??1)===0,'Source enabled state must remain independent from the selected local source type.');
    $service->saveLocalConfig('docs',true);wiki_local_integration_assert(($repo->source()['source_type']??'')==='local'&&($repo->source()['active_source_type']??'')==='github','Saving a local configuration must persist the configured type without replacing the active GitHub cache.');$service->sync();$localIndex=wiki_local_integration_index($server);$localContent=(string)file_get_contents($base.'/storage/wiki/content/README.md');
    wiki_local_integration_assert(($repo->source()['source_type']??'')==='local'&&($repo->source()['active_source_type']??'')==='local'&&$repo->page('index')!==null,'A local sync must activate the configured local source.');

    $service->saveConfig('ChobitsChii','ModulNest','main','docs',true);wiki_local_integration_assert((string)file_get_contents($base.'/storage/wiki/content/README.md')===$localContent&&($repo->source()['source_type']??'')==='github'&&($repo->source()['active_source_type']??'')==='local','Changing local to GitHub configuration must not replace cached Wiki content before sync.');
    $source=$repo->source();$archive=wiki_local_integration_zip($base);$service->syncArchive($source,$archive,str_repeat('a',40));$githubIndex=wiki_local_integration_index($server);wiki_local_integration_assert($githubIndex===$localIndex&&($repo->source()['active_source_type']??'')==='github','The same local tree and GitHub archive fixture must produce identical Wiki pages and assets.');

    $replacement=tempnam(sys_get_temp_dir(),'wiki-local-replacement-');$zip=new ZipArchive();$zip->open($replacement,ZipArchive::OVERWRITE);$zip->addFromString('fixture/docs/README.md','# GitHub replacement');$zip->close();$service->syncArchive($repo->source(),(string)file_get_contents($replacement),str_repeat('b',40));unlink($replacement);wiki_local_integration_assert(str_contains((string)file_get_contents($base.'/storage/wiki/content/README.md'),'GitHub replacement'),'GitHub sync must activate its complete replacement only after successful processing.');
    $service->saveLocalConfig('docs',true);wiki_local_integration_assert(str_contains((string)file_get_contents($base.'/storage/wiki/content/README.md'),'GitHub replacement')&&($repo->source()['source_type']??'')==='local'&&($repo->source()['active_source_type']??'')==='github','Changing GitHub to local configuration must preserve the GitHub cache until local sync.');$service->sync();wiki_local_integration_assert((string)file_get_contents($base.'/storage/wiki/content/README.md')===$localContent&&($repo->source()['active_source_type']??'')==='local','A subsequent local sync must activate the local source atomically.');
    try{$service->saveLocalConfig('../../etc',true);wiki_local_integration_assert(false,'An unsafe local source must be rejected.');}catch(RuntimeException){}wiki_local_integration_assert(($repo->source()['source_type']??'')==='local'&&(string)file_get_contents($base.'/storage/wiki/content/README.md')===$localContent,'A rejected source switch must preserve the active source and cache.');
    try{$service->syncArchive($repo->source(),"not a zip",str_repeat('c',40));wiki_local_integration_assert(false,'An invalid replacement archive must fail.');}catch(WikiSyncException){}wiki_local_integration_assert((string)file_get_contents($base.'/storage/wiki/content/README.md')===$localContent,'A failed synchronisation must keep the existing local Wiki cache intact.');
} finally { $server->exec('DROP DATABASE IF EXISTS `'.$database.'`');wiki_local_integration_remove($base); }
fwrite(STDOUT,"Wiki local source integration smoke passed.\n");
